package org.vedu.managerhubfinance.persistence.model.groupperson;

public enum PersonType {
	CUSTOMER_PESSOA_FISICA,
	CUSTOMER_PESSOA_JURIDICA,
	CUSTOMER_PESSOA_ESTRANGEIRA,
	SUPPLIER_PESSOA_FISICA,
	SUPPLIER_PESSOA_JURIDICA,
	SUPPLIER_PESSOA_ESTRANGEIRA,
	COLLABORATOR;
}
